### ISSUE TITLE
When defining an array incorrectly we dont get a nice error

### ISSUE THREAD

**Issue by em00k** [boriel/zxbasic#169]
`dim test(10,1) as ubyte => {{0,0,0,0,0,0,0,0,0,0,0}}
`
produces this error : 
```

Traceback (most recent call last):
  File "C:\NextBuildv4\zxbc\zxb.py", line 339, in <module>
    sys.exit(main())  # Exit
  File "C:\NextBuildv4\zxbc\zxb.py", line 244, in main
    debug=(OPTIONS.Debug.value > 2))
  File "C:\NextBuildv4\zxbc\ply\yacc.py", line 331, in parse
    return self.parseopt(input, lexer, debug, tracking, tokenfunc)
  File "C:\NextBuildv4\zxbc\ply\yacc.py", line 823, in parseopt
    p.callable(pslice)
  File "C:\NextBuildv4\zxbc\zxbparser.py", line 760, in p_arr_decl_initialized
    if check_bound(p[4].children, p[8]):
  File "C:\NextBuildv4\zxbc\zxbparser.py", line 746, in check_bound
    syntax_error(p.lineno(9), 'Mismatched vector size. Expected %i elements, got %i.' % (boundlist[0].count,
  File "C:\NextBuildv4\zxbc\ply\yacc.py", line 257, in lineno
    return getattr(self.slice[n], 'lineno', 0)
IndexError: list index out of range

```

While you might be able to figure out where the issues is it seems the 'Mismatched vector size. Expected %i elements, got %i.' does not get printed to the console.

**Comment by boriel** [comment]
This is a regression. Let's fix it.

**Comment by boriel** [comment]
The bug has been fixed. Can you download from http://www.boriel.com/wiki/en/index.php/ZX_BASIC:Archive and check if it works, please? :)

**Comment by em00k** [comment]
Yes I can confirm this is now fixed! (Sorry for the delay)
